/// Shared identities, roles, and daemon authentication configuration.
pub mod auth;
pub use auth::{AuthMode, DaemonAuthConfig, Principal, Role};
pub mod api;
pub mod cache_identity;
pub mod canonical_chunker;
mod caption_chunker;
pub mod chunker;
pub mod collection;
pub mod config;
pub mod context;
pub mod deletion;
pub mod embed;
#[path = "types_evidence_spans.rs"]
pub mod evidence_spans;
pub mod generate;
pub mod graph_extraction;
pub mod graphrag;
pub mod image_limits;
pub mod index;
pub mod index_gc;
pub mod index_profile_delete;
pub mod ingest;
pub mod ingest_security;
pub mod memory_budget;
pub mod ocr;
pub mod parser;
pub mod profiles;
pub mod provider;
pub mod resource;
pub mod retrieve;
pub mod store;
pub mod task;
pub mod traits;
pub mod types;
pub mod upstream;
pub mod vision_caption;
